//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Request_ManagerEntities4 : DbContext
    {
        public Request_ManagerEntities4()
            : base("name=Request_ManagerEntities4")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RM_Request> RM_Request { get; set; }
        public virtual DbSet<RM_Status_Table> RM_Status_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
