//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class RM_Request
    {
        public int RTID_Request { get; set; }
        public string RT_Request_Description { get; set; }
        public Nullable<System.DateTime> RT_Request_Registered_DateTime { get; set; }
        public Nullable<System.DateTime> RT_Request_Finished_Date { get; set; }
        public int RT_Status_ID { get; set; }
        public string RT_Document_Name { get; set; }
        public string RT_Document_Content { get; set; }
        public System.DateTime RT_Request_Taken_Date { get; set; }
        public string RT_Title { get; set; }

        public HttpPostedFileBase File { get; set; }

        [NotMapped]
        public string Status { get; set; }
        [NotMapped]
        public string Simple_Name { get; set; }

        public virtual RM_Status_Table RM_Status_Table { get; set; }
    }
}