//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_Status_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RM_Status_Table()
        {
            this.RM_Request = new HashSet<RM_Request>();
        }
    
        public int ST_ID_Status { get; set; }
        public string ST_Status_Name { get; set; }
        public string ST_Status_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RM_Request> RM_Request { get; set; }
    }
}
